name: 'Hollow World '
favicon: null
layout_spectrum: 0.5391660132445395
typography_spectrum: 0.30649
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#11505f'
    - '#03080b'
    - '#2e7c86'
    - '#d7d7d7'
    - '#7fb4a0'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
